server:
  port: 8080

spring:
  datasource:
    url: jdbc:dm://111.0.82.17:8890/DEV_DB
    username: DEV_DB
    password: bwt@1qaz!QAZ
    driver-class-name: dm.jdbc.driver.DmDriver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        format_sql: true

app:
  upload-dir: uploads
