server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./data/drone-change
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

app:
  upload-dir: uploads
