server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${DM_DATASOURCE_URL:jdbc:dm://localhost:5236/DRONE_CHANGE}
    username: ${DM_DATASOURCE_USERNAME:SYSDBA}
    password: ${DM_DATASOURCE_PASSWORD:SYSDBA}
    driver-class-name: dm.jdbc.driver.DmDriver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    open-in-view: false
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        format_sql: true

app:
  upload-dir: ${APP_UPLOAD_DIR:uploads}
